variables:
  BuildType: Debug

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: CMake@1
  displayName: 'Configure'
  inputs:
    cmakeArgs: '.. -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=$(BuildType)'
- task: MSBuild@1
  displayName: 'Build'
  inputs:
    solution: build/win_handle_getter.sln
    msbuildArguments: '/m /p:Configuration=$(BuildType)'
- script: |
        ctest --output-on-failure -C $(BuildType) --timeout 30

  workingDirectory: build
  failOnStderr: true
  displayName: 'Test'
