strategy:
  matrix:
    vs2017:
      imageName: 'vs2017-win2016'
      generator: 'Visual Studio 15 2017 Win64'
    vs2019:
      imageName: 'windows-2019'
      generator: 'Visual Studio 16 2019'


variables:
  BuildType: Debug

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  displayName: 'Configure'
  inputs:
    cmakeArgs: '.. -G "$(generator)"'
- task: CMake@1
  displayName: 'Build'
  inputs:
    cmakeArgs: '--build . --config $(BuildType)'
- script: |
        ctest --output-on-failure -C $(BuildType) --timeout 30 -T test

  workingDirectory: build
  continueOnError: true
  displayName: 'Test'
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'cTest'
    testResultsFiles: 'build/Testing/**/Test.xml'
    failTaskOnFailedTests: true
